apiVersion: v1
kind: Secret
metadata:
  name: instana-registry
data:
  .dockerconfigjson:
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: instana-secrets
data:
  tls.key: 
  tls.crt: 
  dhparams.pem: 
  saml.pem:
  saml.key.pass: 
  adminPassword: 
type: Opaque