apiVersion: instana.io/v1alpha1
kind: Core
metadata:
  name: instana-core
spec:
  databaseLocations:
    - serviceName: "cassandra"
      namespace: "default"
      type: "cassandra"
      isCluster: true
      schemas: ["profiles", "spans", "metrics"]
    - serviceName: "elasticsearch"
      namespace: "default"
      type: "elasticsearch"
      isCluster: true
      schemas: ["metadata"]
    - serviceName: "cockroachdb"
      namespace: "default"
      type: "cockroachdb"
      isCluster: true
      schemas: ["butlerdb", "tenantdb", "sales"]
    - serviceName: "clickhouse"
      type: "clickhouse"
      isCluster: true
      namespace: "default"
      schemas: ["clickhouse"]
      clusterName: "local"
      clusterNodes: ["", ""]
    - serviceName: "kafka"
      type: "kafka"
      isCluster: true
      namespace: "default"
      schemas: ["ingress"]
    - serviceName: "zookeeper"
      type: "zookeeper"
      isCluster: true
      namespace: "default"
      schemas: ["ingress"]
