bases:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: instana-registry
    files:
      - "secret/.dockerconfigjson"
    type: "kubernetes.io/dockerconfigjson"

