apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  clusterIP: None
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 9042
      targetPort: 9042
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cassandra
subsets:
  - addresses:
      - ip: DB_HOST
    ports:
      - port: 9042
        name: "tcp"