namespace: unit-namespace

#namePrefix: 

commonLabels:
  app: instana
  group: core

secretGenerator:
- name: app-tls
  files:
    - "secret/tls.cert"
    - "secret/tls.key"
  type: "kubernetes.io/tls"

resources:
  - cassandra-service.yaml
  - clickhouse-service.yaml
  - cockroachdb-service.yaml
  - elasticsearch-service.yaml
  - kafka-service.yaml
  - zookeeper-service.yaml
  - secrets.yaml
  - loadbalancer.yaml
  #- volume.yaml
