apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  clusterIP: None
  ports:
    - name: "http"
      protocol: "TCP"
      port: 9200
      targetPort: 9200
    - name: "tcp"
      protocol: "TCP"
      port: 9300
      targetPort: 9300
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch
subsets:
  - addresses:
      - ip: ${DB_HOST}
    ports:
      - port: 9300
        name: "tcp"
