apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  clusterIP: None
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 2181
      targetPort: 2181
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zookeeper
subsets:
  - addresses:
      - ip: "$(DB_HOST)"
    ports:
      - port: 2181
        name: "tcp"
