bases:
  - ../../base

namespace: namespace-unit

secretGenerator:
  - name: instana-secrets
    files:
      - "./secret/tls.crt"
      - "./secret/tls.key"
      - "./secret/dhparams.pem"
      - "./secret/license"
    literals:
      - adminPassword=secretPWD
    type: "Opaque"
  - name: instana-registry
    files:
      - "./secret/.dockerconfigjson"
    type: "kubernetes.io/dockerconfigjson"

patchesStrategicMerge:
  - unit-lb-ip.yaml

resources:
  - namespace.yaml
