apiVersion: apps/v1
kind: Deployment
metadata:
  name: instana-selfhosted-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: instana-selfhosted-operator
  template:
    metadata:
      labels:
        name: v-operator
    spec:
      serviceAccountName: instana-selfhosted-operator
      containers:
        - name: instana-selfhosted-operator
          # Replace this with the built image name
          image: containers.instana.io/instana/prerelease/selfhosted/operator:latest
          args:
            - '--zap-level=1'
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "instana-selfhosted-operator"
      imagePullSecrets:
        - name: instana-registry

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: instana-selfhosted-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumes
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - namespaces
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - instana-selfhosted-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - selfhosted.instana.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - instana.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instana-selfhosted-operator
subjects:
  - kind: ServiceAccount
    name: instana-selfhosted-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: instana-selfhosted-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instana-selfhosted-operator

