apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: instana-preflight
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.15.0"
              message: Instana requires at least Kubernetes 1.15.0, and recommends 1.19.0.
              uri: https://kubernetes.io
          - warn:
              when: "< 1.19.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.19.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - distribution:
        outcomes:
          - pass:
              when: "== gke"
              message: GKE is a supported platform
          - pass:
              when: "== aks"
              message: AKS is a supported platform
          - pass:
              when: "== eks"
              message: EKS is a supported platform
          - fail:
              when: "== docker-desktop"
              message: Instana does not support Docker Desktop
          - fail:
              when: "== microk8s"
              message: Instana does not support Microk8s
          - fail:
              when: "== minikube"
              message: Instana does not support Minikube
          - warn:
              message: Your Kubernetes platform is not validated, but there might be compatibility issues.
    - nodeResources:
        checkName: Cluster Size
        outcomes:
          - fail:
              when: "count() < 3"
              message: Instana requires at least 3 nodes
          - pass:
              message: Your cluster has enough nodes.
    - nodeResources:
        checkName: Cluster Resources
        filters:
          allocatableMemory: 16Gi
          cpuCapacity: "8"
        outcomes:
          - fail:
              when: "count() < 3"
              message: Cannot find enough a nodes with sufficient memory and CPU
          - pass:
              message: Your have sufficient CPU and memory available.